name: Run Ladder System

on:
  workflow_dispatch:  # Manual trigger only

  # Uncomment the following block to enable automatic runs
  # schedule:
  #   - cron: '*/15 * * * *'  # Every 15 minutes (UTC)

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Write credentials to /tmp
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}" | base64 -d > /tmp/google-credentials.json


      - name: Build the application (skip tests)
        run: ./mvnw clean package -DskipTests=true


      - name: Run the application
        run: java -jar target/*.jar --google.credentials.file=/tmp/google-credentials.json

